### ISSUE TITLE
Solution file links all broken

### ISSUE THREAD

**Issue by zdrossman** [learn-co-curriculum/search-and-shout#3]
Effectively it looks as if when we ran git merge master for the cleanup, it duplicated all the files and didn't know what to do with the pbxproj. I'd suggest simply resetting hard to the commit before, then moving the files on solution branch one folder "up" and then doing the merge master again to reduce the confusion that git seems to be having with this.

**Comment by AnnJohn** [comment]
PR [#5] (https://github.com/learn-co-curriculum/search-and-shout/pull/5) closes the issue
